name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t dev-ops-project .

      - name: Run Docker container
        run: docker run -d --name app -p 8080:8080 dev-ops-project

      - name: Wait for application to start
        run: sleep 10

      - name: Test application
        run: curl -f http://localhost:8080 || exit 1
        